# Ansible execution environment test manifest
apiVersion: v1
kind: Pod
metadata:
  name: ansible-execution-environment
spec:
  # securityContext:
  #   runAsUser: 46487
  #   runAsGroup: 1006
  containers:
  - name: ansible-execution-environment
    image: pnispero/deploy-env:latest
    imagePullPolicy: Always
    # start the build script
    command: ["/bin/sh"]
    args:
      - -c
      - >-
          echo "$ cd /build/" &&
          cd /build/ && 
          echo "$ pwd && ls" &&
          pwd && ls &&
          sleep infinity
    # && echo "$ python3 start_build.py" &&
    # python3 start_build.py &&
    # echo "$ sleep to keep container alive for debug" &&
    # sleep infinity
    env:
    - name: ADBS_SOURCE
      value: /mnt/eed/ad-build/scratch/test-ioc
      # value: /mnt/build-scratch/ad-build/test-ioc-main
    - name: ADBS_OUTPUT
      value: /mnt/eed/ad-build/scratch/test-ioc
      # value: /mnt/build-scratch/ad-build/test-ioc-main/output
    - name: ADBS_OS_ENVIRONMENT
      value: rocky9
    resources:
      limits:
        memory: 8Gi
        cpu: 4000m