# Volume mount deploy test from Claudio
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3df-dev-container-ad-group
spec:
  storageClassName: sdf-group-ad
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3df-dev-container1
spec:
  selector:
    matchLabels:
      app: s3df-dev-container1
  template:
    metadata:
      labels:
        app: s3df-dev-container1
      annotations:
        app: s3df-dev-container1
    spec:
      containers:
      - name: s3df-dev-container1
        image: redhat/ubi8:latest
        imagePullPolicy: Always
        command: [sleep]
        args: ['infinity']
        # envFrom:
        # - configMapRef:
        #     name: epics-env-config
        volumeMounts:
        - name: s3df-dev-container-ad-group
          mountPath: /mnt
        resources:
          limits:
            memory: 8Gi
            cpu: 4000m
      volumes:
      - name: s3df-dev-container-ad-group
        persistentVolumeClaim:
          claimName: s3df-dev-container-ad-group