apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3df-dev-container-ad-group
spec:
  storageClassName: sdf-group-ad
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-build-rhel8-dev-deployment
spec:
  selector:
    matchLabels:
      app: test-build-rhel8-dev-deployment
  template:
    metadata:
      labels:
        app: test-build-rhel8-dev-deployment
      annotations:
        app: test-build-rhel8-dev-deployment
    spec:
      securityContext:
        runAsUser: 46487
        runAsGroup: 1006
      containers:
      - name: test-build-rhel8-dev-deployment
        image: pnispero/rocky9-env:dev
        imagePullPolicy: Always
        # start the build script
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              echo "$ cd /build/" &&
              cd /build/ && 
              echo "$ pwd && ls" &&
              pwd && ls &&
              echo "$ python3 start_build.py" &&
              python3 start_build.py &&
              echo "$ sleep to keep container alive for debug" &&
              sleep infinity
        # envFrom:
        # - configMapRef:
        #     name: epics-env-config
        env:
        - name: ADBS_SOURCE # From backend
          value: /mnt/eed/ad-build/scratch/test-ioc-main-pnispero/test-ioc
          # value: /mnt/build-scratch/ad-build/test-ioc-main
        - name: ADBS_OS_ENVIRONMENT # From backend
          value: rhel8
        - name: ADBS_COMPONENT # From CLI
          value: test-ioc
        - name: ADBS_BRANCH # From CLI
          value: main
        volumeMounts:
        - name: s3df-dev-container-ad-group
          mountPath: /mnt
        resources:
          limits:
            memory: 8Gi
            cpu: 4000m
      volumes:
      - name: s3df-dev-container-ad-group
        persistentVolumeClaim:
          claimName: s3df-dev-container-ad-group




