apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3df-dev-container-ad-group
spec:
  storageClassName: sdf-group-ad
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: rhel7-dev-oscilloscope
spec:
  securityContext:
    runAsUser: 46487
    runAsGroup: 1006
  containers:
  - name: rhel7-dev-oscilloscope
    image: ghcr.io/ad-build-test/rhel7-env:dev
    imagePullPolicy: Always
    # start the build script
    command: ["/bin/sh"]
    args:
      - -c
      - >-
          echo "$ cd /build/" &&
          cd /build/ && 
          echo "$ pwd && ls" &&
          pwd && ls &&
          echo "$ python3 start_build.py" &&
          python3 start_build.py &&
          echo "$ sleep to keep container alive for debug" &&
          sleep infinity
    env:
    - name: ADBS_SOURCE # From backend
      value: /mnt/eed/ad-build/scratch/oscilloscope-test-pnispero/oscilloscope
    - name: ADBS_OS_ENVIRONMENT # From backend
      value: rhel7
    - name: ADBS_COMPONENT # From CLI
      value: oscilloscope
    - name: ADBS_BRANCH # From CLI
      value: main
    volumeMounts:
    - name: s3df-dev-container-ad-group
      mountPath: /mnt
    - name: podman-storage
      mountPath: /var/lib/containers/storage  # Mount point for Podman storage
    resources:
      limits:
        memory: 8Gi
        cpu: 4000m
  volumes:
  - name: s3df-dev-container-ad-group
    persistentVolumeClaim:
      claimName: s3df-dev-container-ad-group
  - name: podman-storage
    emptyDir: {}  # Use an emptyDir volume for storage
