apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3df-dev-container-ad-group
spec:
  storageClassName: sdf-group-ad
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: rocky9-test
spec:
  containers:
  - name: rocky9-test
    image: pnispero/rocky9-env:dev
    # start the build script
    command: ["/bin/sh"]
    args:
      - -c
      - >-
          echo "$ cd /build/" &&
          cd /build/ && 
          echo "$ pwd && ls" &&
          pwd && ls &&
          echo "$ python3 start_build.py" &&
          python3 start_build.py &&
          echo "$ sleep to keep container alive for debug" &&
          sleep infinity
    env:
    - name: ADBS_SOURCE
      value: /mnt/eed/ad-build/scratch/test-ioc
      # value: /mnt/build-scratch/ad-build/test-ioc-main
    - name: ADBS_OUTPUT
      value: /mnt/eed/ad-build/scratch/test-ioc
      # value: /mnt/build-scratch/ad-build/test-ioc-main/output
    - name: ADBS_OS_ENVIRONMENT
      value: rocky9
    volumeMounts:
    - name: s3df-dev-container-ad-group
      mountPath: /mnt
    resources:
      limits:
        memory: 8Gi
        cpu: 4000m
  volumes:
  - name: s3df-dev-container-ad-group
    persistentVolumeClaim:
      claimName: s3df-dev-container-ad-group