apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3df-dev-container-ad-group
spec:
  storageClassName: sdf-group-ad
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-build-rocky9-podman
spec:
  securityContext:
    runAsUser: 46487
    runAsGroup: 1006
  containers:
  - name: test-build-rocky9-podman
    image: ghcr.io/ad-build-test/rocky9-env:podman
    imagePullPolicy: Always
    # start the build script
    command: ["/bin/sh"]
    args:
      - -c
      - >-
          echo "$ sleep to keep container alive for debug" &&
          sleep infinity
    env:
    - name: ADBS_SOURCE
      value: /mnt/eed/ad-build/scratch/test-ioc
      # value: /mnt/build-scratch/ad-build/test-ioc-main
    - name: ADBS_OUTPUT
      value: /mnt/eed/ad-build/scratch/test-ioc
      # value: /mnt/build-scratch/ad-build/test-ioc-main/output
    - name: ADBS_OS_ENVIRONMENT
      value: rocky9
    volumeMounts:
    - name: s3df-dev-container-ad-group
      mountPath: /mnt
    resources:
      limits:
        memory: 8Gi
        cpu: 4000m
  volumes:
  - name: s3df-dev-container-ad-group
    persistentVolumeClaim:
      claimName: s3df-dev-container-ad-group