# Used for rpm building installing testing
# Run as ROOT to install rpms as well
# No volume mounts needed, can get dependencies using artifact api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpm-rhel8-dev
spec:
  selector:
    matchLabels:
      app: rpm-rhel8-dev
  template:
    metadata:
      labels:
        app: rpm-rhel8-dev
      annotations:
        app: rpm-rhel8-dev
    spec:
      containers:
      - name: rpm-rhel8-dev
        image: pnispero/rhel8-env:latest
        imagePullPolicy: Always
        # start the build script
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              echo "$ cd /build/" &&
              cd /build/ && 
              echo "$ pwd && ls" &&
              pwd && ls &&
              echo "$ sleep to keep container alive for debug" &&
              sleep infinity
        # envFrom:
        # - configMapRef:
        #     name: epics-env-config
        env:
        - name: ADBS_SOURCE # From backend
          value: /build/test-ioc
          # value: /mnt/build-scratch/ad-build/test-ioc-main
        - name: ADBS_OS_ENVIRONMENT # From backend
          value: rhel8
        - name: ADBS_COMPONENT # From CLI
          value: test-ioc
        - name: ADBS_BRANCH # From CLI
          value: main
        resources:
          limits:
            memory: 8Gi
            cpu: 4000m




