apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3df-dev-container-ad-group
spec:
  storageClassName: sdf-group-ad
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-build-container
spec:
  selector:
    matchLabels:
      app: ad-build-container
  template:
    metadata:
      labels:
        app: ad-build-container
      annotations:
        app: ad-build-container
    spec:
      containers:
      - name: ad-build-container
        image: pnispero/rocky9-env:latest
        imagePullPolicy: Always
        # start the build script
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              echo "$ cd /build/" &&
              cd /build/ && 
              echo "$ pwd && ls" &&
              pwd && ls &&
              echo "$ python3 start_build.py" &&
              python3 start_build.py &&
              echo "$ sleep 9999 to keep container alive for debug" &&
              sleep 9999
        # envFrom:
        # - configMapRef:
        #     name: epics-env-config
        env:
        - name: ADBS_SOURCE
          value: /mnt/eed/ad-build/test-ioc
          # value: /mnt/build-scratch/ad-build/test-ioc-main
        - name: ADBS_OUTPUT
          value: /mnt/eed/ad-build/test-ioc/output
          # value: /mnt/build-scratch/ad-build/test-ioc-main/output
        - name: ADBS_OS_ENVIRONMENT
          value: rocky9
        volumeMounts:
        - name: s3df-dev-container-ad-group
          mountPath: /mnt
        resources:
          limits:
            memory: 8Gi
            cpu: 4000m
      volumes:
      - name: s3df-dev-container-ad-group
        persistentVolumeClaim:
          claimName: s3df-dev-container-ad-group




