# This is for testing the image the artifact api service built
apiVersion: v1
kind: Pod
metadata:
  name: test-ioc-dev
spec:
  containers:
    - name: podman
      image: ghcr.io/ad-build-test/test-ioc-dev-patrick-rocky9:latest
      imagePullPolicy: Always
      command: ["/bin/sh"]
      args:
        - -c
        - >-
            echo "$ sleep to keep container alive for debug" &&
            sleep infinity
