# apiVersion: v1 # Used to authorize to kubernetes cluster
# kind: ServiceAccount
# metadata:
#   name:  core-build-system-sa
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: core-build-system-rb
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: edit
# subjects:
#   - kind: ServiceAccount
#     name: core-build-system-sa
# ---
apiVersion: apps/v1 # App deployment
kind: Deployment
metadata:
  name: artifact-api-service
  namespace: artifact
spec:
  selector:
    matchLabels:
      app: artifact-api-service
  template:
    metadata:
      labels:
        app: artifact-api-service
    spec:
      serviceAccountName: myexample-sa
      containers:
      - name: artifact-api-service
        image: pnispero/artifact-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  
