apiVersion: v1
kind: Pod
metadata:
  name: test-ioc-dev
spec:
  containers:
    - name: podman
      image: pnispero/test-ioc-dev-patrick-rocky9:latest
      imagePullPolicy: Always
      command: ["/bin/sh"]
      args:
        - -c
        - >-
            echo "$ sleep to keep container alive for debug" &&
            sleep infinity
