apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-workspace
  namespace: github-runner-test
spec:
  storageClassName: wekafs--sdf-k8s01
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
