namespace: my-namespace
namePrefix: dev-
nameSuffix: "-001"
commonLabels:
  app: bingo
commonAnnotations:
  oncallPager: 800-555-1212
images:
  - name: TEMPLATE-IMAGE
    newName: image-from-kustomization
resources:
- deployment.yaml
