# Do a kubectl describe -n artiface secrets to get your secret
# TODO: Try cluster role binding if role binding doesnt work
apiVersion: v1
kind: ServiceAccount
metadata:
  name: artifact-sa
  namespace: artifact
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: artifact-role
  namespace: artifact
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: artifact-rb
  namespace: artifact
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: artifact-role
subjects:
- kind: ServiceAccount
  name: artifact-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: artifact-sa-token
  namespace: artifact
  annotations:
    kubernetes.io/service-account.name: artifact-sa
type: kubernetes.io/service-account-token