apiVersion: apps/v1 # App deployment
kind: Deployment
metadata:
  name: artifact-api-service
  namespace: artifact
spec:
  selector:
    matchLabels:
      app: artifact-api-service
  template:
    metadata:
      labels:
        app: artifact-api-service
    spec:
      securityContext:
        runAsUser: 46487
        runAsGroup: 1006
      serviceAccountName: artifact-sa
      containers:
      - name: artifact-api-service
        image: pnispero/artifact-api:latest
        imagePullPolicy: Always
        # start the build script
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              echo "$ cd /app/" &&
              cd /app/ && 
              echo "$ pwd && ls" &&
              pwd && ls &&
              echo "$ ./startup.sh" &&
              ./startup.sh
        ports:
        - containerPort: 8080  
        env:
        - name: artifact_api_token
          valueFrom: 
            secretKeyRef:
              name: artifact-sa-token
              key: token
        volumeMounts:
        - name: s3df-dev-container-ad-group
          mountPath: /mnt
      volumes:
      - name: s3df-dev-container-ad-group
        persistentVolumeClaim:
          claimName: s3df-dev-container-ad-group

