apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-controller
  template:
    metadata:
      labels:
        app: deployment-controller
    spec:
      containers:
      - name: deployment-controller
        image: pnispero/deployment-controller:latest
        imagePullPolicy: Always
        # start the build script
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              echo "$ cd /app/" &&
              cd /app/ && 
              echo "$ pwd && ls" &&
              pwd && ls &&
              echo "$ fastapi run /app/deployment_controller.py --port 80" &&
              fastapi run /app/deployment_controller.py --port 80
        ports:
        - containerPort: 80  

