# There is an error with line endings when grabbing key from vault
# apiVersion: ricoberger.de/v1alpha1
# kind: VaultSecret
# metadata:
#   name: deployment-controller-secrets
# spec:
#   path: secret/ad/ad-build-dev/core-build-system/deployment-controller
#   type: Opaque
#   keys:
#     - S3DF_SSH_KEY
