apiVersion: v1
kind: ConfigMap
metadata:
  name: build-config
data:
  start_build.py: |
    import json
    import os
    print('Hello World')
    print(os.getcwd())
    print('Print contents of build_config.json:')
    with open('build_config.json') as f:
        d = json.load(f)
        print(d)

  build_config.json: | # TODO: This part should be dynamically filled
    {
      "ADBS_COMPONENT": "hello_world",
      "ADBS_BRANCH": "fix-1234",
      "ADBS_LINUX_USER": "katzung",
      "ADBS_GH_USER": "katzung-slac",
      "ADBS_BUILD_COMMAND": "make"
    }