# Deployment for a build pod - this is a prototype
apiVersion: v1
kind: Pod
metadata:
  name: test-build
spec:
  containers:
  - name: test-build
    image: pnispero/rocky9-env:latest
    # start the build script
    command: ["/bin/sh"]
    args:
      - -c
      - >- # cd is PRoblematic because /etc/build isn't mounted yet, sleep maybe?
          python3 /etc/build/start_build.py 
    volumeMounts:
    - name: build
      mountPath: "/etc/build"
      readOnly: true
  volumes:
  - name: build
    configMap:
      name: build-config
      # An array of keys from the ConfigMap to create as files
      items:
      - key: "start_build.py"
        path: "start_build.py"
      - key: "build_config.json"
        path: "build_config.json"
# TODO
#     # see if we can get the build system scripts MAPPEd not baked into the containers
#     # good for maintenance

# Get the script done, image ready, and this deployment ready which calls the image
# and the build script